{{- /* SPDX-License-Identifier: Apache-2.0 */ -}}
{{- /* The whole of THIRD_PARTY_LICENSES is rendered from this template by
       `make license-report`. Edit the template; never the output. */ -}}
Third-party attributions for Mockulus
=====================================

Generated by `make license-report` from the module graph of the shipped binary
(go-licenses). CI regenerates it and fails on a diff, so this file cannot be
correct on the day it is written and quietly wrong a year later (SPEC §22.1).

Every module below classifies under one of Apache-2.0, MIT, BSD-2-Clause,
BSD-3-Clause or ISC. Copyleft (GPL/LGPL/AGPL/MPL) is denied for this graph with
no exceptions, and so is a license go-licenses cannot classify — a custom-worded
text reads as Unknown and hard-fails the gate.

Nothing is vendored into this repository. The templating engine of SPEC §10.1
and the JSONPath evaluator of §6.7 were both planned as dependencies and are
mockulus-authored instead, under Apache-2.0 like the rest of the tree, so there
is no hand-curated section here to drift.
{{ range . }}
--------------------------------------------------------------------------------
{{ .Name }}
License: {{ .LicenseName }}
{{ if .LicenseURL }}Source:  {{ .LicenseURL }}{{ end }}
{{ end }}
