{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{/* Template for the module-derived section of THIRD_PARTY_LICENSES. */}}
Module-derived attributions, generated by go-licenses.
Do not edit by hand; the curated vendored section lives in THIRD_PARTY_LICENSES.

{{ range . }}
--------------------------------------------------------------------------------
{{ .Name }}
License: {{ .LicenseName }}
{{ if .LicenseURL }}Source:  {{ .LicenseURL }}{{ end }}
{{ end }}
