{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.couchbase.connstr (not .Values.couchbase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockulus.couchbaseSecret" . }}
  labels:
    {{- include "mockulus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.couchbase.usernameKey }}: {{ required "couchbase.username is required when couchbase.connstr is set and no existingSecret is given" .Values.couchbase.username | quote }}
  {{ .Values.couchbase.passwordKey }}: {{ required "couchbase.password is required when couchbase.connstr is set and no existingSecret is given" .Values.couchbase.password | quote }}
{{- end }}
{{- if and .Values.adminAuth.token (not .Values.adminAuth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockulus.adminAuthSecret" . }}
  labels:
    {{- include "mockulus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.adminAuth.tokenKey }}: {{ .Values.adminAuth.token | quote }}
{{- end }}
{{- if and .Values.tracing.enabled .Values.tracing.headers (not .Values.tracing.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mockulus.tracingSecret" . }}
  labels:
    {{- include "mockulus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tracing.headersKey }}: {{ .Values.tracing.headers | quote }}
{{- end }}
